### ISSUE TITLE
Need upgrade version 2.6 for the last version - http://denyhosts.sourceforge.net

### ISSUE THREAD

**Issue by ZerooCool** [denyhosts/denyhosts#137]
Need upgrade version 2.6 for the last version

http://denyhosts.sourceforge.net

**Comment by josev814** [comment]
I don't have control over that site.  That's managed by Phil Schwartz, and talking with him he has pretty much abandoned the site/project.  I've been working on getting the documentation ported from that site over to the Wiki on GitHub.

**Comment by adriel** [comment]
@josev814 Do you know if Phil has any plans to link to this fork from his old Sourceforge site or something?
Because the other day I googled DenyHosts and the first few links all refer to the original project and there is little (if any?) mention that it's no longer being maintained and that there is a new fork which is still active with a working sync server.
There still seems to be people (or bots?) [downloading v2.6](https://sourceforge.net/projects/denyhosts/files/) from 2008 looking at the Sourceforge page.
Only in the wiki, there is a mention of forks.

**Comment by josev814** [comment]
I sent Phil an e-mail to see if he could put the new package in place, or if I could be added as a maintainer on sourceforge.

**Comment by josev814** [comment]
There's also a denyhosts project at https://sourceforge.net/projects/denyhost/ that belongs to @slicer69

**Comment by slicer69** [comment]
The DenyHost project was just a vehicle for distributing this project in tarball format with more detailed updates. At the top of the home page it links back to this GitHub repo.

**Comment by josev814** [comment]
Phil granted me admin access to denyhosts on sourceforge.  I just need to figure out how to update stuff on that platform, since I haven't used it previously.

**Comment by josev814** [comment]
@slicer69 do you want me to add you to the SourceForge project?

**Comment by josev814** [comment]
Packages are updated on SourceForge now
