### ISSUE TITLE
update-rc.d: error: denyhosts Default-Start contains no runlevels, aborting

### ISSUE THREAD

**Issue by ZerooCool** [denyhosts/denyhosts#156]
This command could be useless, in any case, for the moment, it is not used nor essential to validate the installation of DenyHosts : https://github.com/denyhosts/denyhosts/commit/98d2bb9ffd4c0bb4af91a9d4332b4a7566296376#diff-d396f81f39f45168d5772b9c65688525

`sudo systemctl enable denyhosts`

It was observed on an old tutorial.

```
denyhosts.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable denyhosts
update-rc.d: error: denyhosts Default-Start contains no runlevels, aborting.
```

So I left this note in comment, on the manual documentation that I proposed to install DenyHosts.
I have not, for the moment, sought to understand further the cause of this problem.

**Comment by josev814** [comment]
I saw that when you did your symlink, you symlinked the daemon-control.  Do you see the denyhosts.service file anywhere.  In our repo we have the denyhosts.service file, and if you simply copy that into /etc/systemd/system and then run systemctl enable denyhosts.service, the systemd and service commands should work as expected.  I just tested it out myself.

**Comment by josev814** [comment]
If you can't see it on your system, it might be something that's missing during the rpm build process and deb conversion that I'm doing for debian.

**Comment by ZerooCool** [comment]
Ok i see : denyhosts.service
But, in the folder : /usr/share/denyhosts
Not in the folder : /etc/init.d/

Then, yes : " it might be something that's missing during the rpm build process and deb conversion for debian. "

So I should not, for my part, that I make a link to the daemon, but, to the service? denyhosts.sevice?

Can you confirm then that currently I am running DenyHosts as a Daemon?
So it's not the same as if I ran DenyHosts with denyhosts.sevice?

Despite everything, the two methods allow running denyhosts, are we okay?

If this is the case, I can notify that in my documentation, to differentiate the two approaches, and, on your side, you can see if you manage to correct the installation mechanism?

**Comment by josev814** [comment]
Yes you should either be symlinking to the denyhosts.service file or copying the denyhosts.service file to systemd.

Running denyhosts.service will still run dh as a daemon.  Your are able to run denyhosts as a daemon using python daemon-control.  The service file calls the dh.py file with the daemon flag.  It's just that the service file is made in the format for SystemD to use.  I'm sure that the .service file could even be modified to call the daemon-control file and pass that start parameter to it rather than running dh.py itself.

Either way running denyhosts is working fine.  Just using the service method will prevent errors from occurring saying that there aren't any runlevels or lsb issues.

I have looked at using stdeb to package up dh for debian, which looks promising.  I will create the .service file.  The issue I'm see with it at the moment is that I have to do a force overwrite of the files it they already exist when using dpkg to install the package.  I'm not sure why it's not allowing me to just update the package yet.

**Comment by ZerooCool** [comment]
I have test with the bug_128 branch, but, i can't use enable command.
The last time, i make a stream, then, you can see.

**Comment by ZerooCool** [comment]
enable KO
start OK

_You have 14 day for look this stream_ : https://www.twitch.tv/videos/629638457

**Comment by josev814** [comment]
By the Video above it looks like this issue is resolved. @ZerooCool I'll open up a new issue specifically concerning the Debian .service file/package.

**Comment by ZerooCool** [comment]
Yes for start it's resolved, but, not for the enable command.

I add this link, for the subject " start ".
It's the comment from " Ordinatous SeeYou ", on my stream : https://serverfault.com/questions/849507/systemctl-doesnt-recognize-my-service-default-start-contains-no-runlevels-abo

Ok for close this issue.
