### ISSUE TITLE
Denyhosts doesn't log if run in --foreground mode

### ISSUE THREAD

**Issue by jasontibbitts** [denyhosts/denyhosts#22]
So I'm finally updating the denyhosts package in Fedora.  Systemd prefers that processes it starts not fork themselves into the background, so I can simply pass --foreground instead of --daemon.  But if I do this, it doesn't log anything because it appears to only log in --daemon mode (DenyHosts/util.py setup_logging).

I can patch this rather easily, but I'm not sure what the proper behavior actually is.

**Comment by slicer69** [comment]
Please correct me if I've wrong, but isn't there a configuration option for systemd which tells systemd that a daemon may fork right away? My systemd-ese is rusty, but I think the unit file can be set to something like "start" rather than regular "daemon" mode. That might work around the issue.

Alternatively, I would be in favour of logging whether in daemon or foreground mode. I don't see any good reason not to log while running in the foreground.

**Comment by jasontibbitts** [comment]
There is (Type=forking) and that's what we've been using in the .service file since Fedora 15.  But it is "better" (in the systemd world, at least) to not fork into the background so that systemd knows the pid of the main process directly and doesn't have to rely on pid files.  If I run denyhosts --foreground instead of --daemon it actually runs great; it just doesn't log anything.

**Comment by slicer69** [comment]
I'll take a stab at fixing this so that DenyHosts will log when run in the foreground. I think it probably should anyway.

**Comment by jasontibbitts** [comment]
Thanks.  It's not a huge deal (it works fine as it is and I could patch it trivially) but I just thought it was kind of odd.

**Comment by slicer69** [comment]
I have modified the logging code so DenyHosts always logs, whether in daemon or foreground mode.
